package io.payorch.core.model;

import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Represents the normalized payment request built by the calling application.
 *
 * <p>The {@code transactionId} must be unique per payment attempt and is used
 * to correlate requests with results and webhook events.
 *
 * @param transactionId a unique identifier for this payment, generated by the caller
 * @param amount        the amount to collect
 * @param phoneNumber   the mobile number of the payer (E.164 format recommended)
 * @param description   a human-readable description of the payment purpose
 * @param returnUrl     an optional URL to redirect the payer after completion
 * @param metadata      arbitrary key-value pairs forwarded to the provider where supported
 * @since 0.1.0
 */
public record PaymentRequest(
        String transactionId,
        Money amount,
        String phoneNumber,
        String description,
        Optional<String> returnUrl,
        Map<String, String> metadata) {

    /**
     * Validates and defensively copies the payment request at construction time.
     *
     * @throws NullPointerException if {@code transactionId}, {@code amount},
     *                              {@code phoneNumber}, or {@code description} is null
     */
    public PaymentRequest {
        Objects.requireNonNull(transactionId, "transactionId must not be null");
        Objects.requireNonNull(amount, "amount must not be null");
        Objects.requireNonNull(phoneNumber, "phoneNumber must not be null");
        Objects.requireNonNull(description, "description must not be null");
        metadata = metadata != null ? Map.copyOf(metadata) : Map.of();
    }

    /**
     * Creates a minimal payment request without a return URL or metadata.
     *
     * @param transactionId a unique identifier for this payment
     * @param amount        the amount to collect
     * @param phoneNumber   the mobile number of the payer
     * @param description   a human-readable description
     * @return a new {@code PaymentRequest}
     */
    public static PaymentRequest of(
            String transactionId, Money amount, String phoneNumber, String description) {
        return new PaymentRequest(transactionId, amount, phoneNumber, description,
                Optional.empty(), Map.of());
    }
}